pygmentstitle:            "Yue's Tech Blog"
description:      "Collection of everythings I want to record down especially for tech"
url:              "/categories/index.html"
signoff:          # Your name.
disqus_shortname: "yue"
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    url:          http://466300750.github.io
    external:     true
  - name:         GitHub
    url:          http://github.com/466300750
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
disqus: y
share: y
gitment:
  enable: true
  id: '<%= page.title %>' 
  owner: '466300750'
  repo: '466300750.github.io'
  client_id: '3ae5115d9ccc977c2748'
  client_secret: '2c929c1fc6652518f8dcd0c7412f565895187144'
